"""
Email notification service for student account creation.
Handles sending welcome emails with credentials to newly registered students.
"""

import logging
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings

logger = logging.getLogger(__name__)


def send_student_account_welcome_email(student_user, sr_code, temporary_password):
    """
    Send a welcome email to the newly registered student with login credentials.
    
    Args:
        student_user: User instance with email, first_name, last_name
        sr_code: Student's SR-Code (email username)
        temporary_password: Temporary password generated by system
        
    """
    try:
        # Prepare email context
        context = {
            "full_name": f"{student_user.first_name} {student_user.last_name}",
            "email": student_user.email,
            "sr_code": sr_code,
            "temporary_password": temporary_password,
            "login_url": f"{settings.SITE_URL}/login" if hasattr(settings, 'SITE_URL') else "/login",
            "logo_url": f"{settings.SITE_URL}/static/images/backontrack-logo.png" if hasattr(settings, 'SITE_URL') else "/static/images/backontrack-logo.png",
            "seal_url": f"{settings.SITE_URL}/static/images/bsu-seal.png" if hasattr(settings, 'SITE_URL') else "/static/images/bsu-seal.png",
        }
        
        # Render HTML email template
        html_message = render_to_string(
            "academics/emails/student_welcome.html",
            context
        )
        plain_message = strip_tags(html_message)
        
        # Send email
        send_mail(
            subject="Welcome to Batangas State University - Auto POS System",
            message=plain_message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[student_user.email],
            html_message=html_message,
            fail_silently=False,
        )
        
        logger.info(
            f"Welcome email sent successfully to {student_user.email} "
            f"(SR-Code: {sr_code})"
        )
        return True
        
    except Exception as e:
        logger.error(
            f"Failed to send welcome email to {student_user.email} "
            f"(SR-Code: {sr_code}): {str(e)}",
            exc_info=True
        )
        return False


def send_student_account_welcome_email_async(student_user, sr_code, temporary_password):
    try:
        send_student_account_welcome_email(
            student_user,
            sr_code,
            temporary_password
        )
    except Exception as e:
        # Log the error but don't re-raise to avoid blocking student creation
        logger.error(
            f"Async email sending failed for {student_user.email}: {str(e)}",
            exc_info=True
        )
