# Generated by Django 6.0.4 on 2026-04-30 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('manually_adjusted', 'Manually Adjusted'), ('exported', 'Exported')], default='draft', max_length=30)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pos_plans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_plans', to='academics.student')),
            ],
        ),
        migrations.CreateModel(
            name='POSPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_year_level', models.PositiveIntegerField()),
                ('planned_term', models.CharField(choices=[('first_sem', 'First Semester'), ('second_sem', 'Second Semester'), ('midterm', 'Midterm')], max_length=20)),
                ('display_order', models.PositiveIntegerField()),
                ('is_auto_assigned', models.BooleanField(default=True)),
                ('is_manually_adjusted', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_plan_items', to='academics.course')),
                ('linked_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pos_plan_items', to='academics.studentcourserecord')),
                ('pos_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posplan')),
            ],
            options={
                'ordering': ['planned_year_level', 'display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='posplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='unique_current_pos_plan_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='posplanitem',
            unique_together={('pos_plan', 'course')},
        ),
    ]
