# Generated by Django 6.0.4 on 2026-04-30 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('units', models.PositiveIntegerField()),
                ('is_elective', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_code', models.CharField(max_length=50, unique=True)),
                ('curriculum_name', models.CharField(max_length=150)),
                ('academic_year_label', models.CharField(blank=True, max_length=50, null=True)),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('first_sem', 'First Semester'), ('second_sem', 'Second Semester'), ('midterm', 'Midterm')], max_length=20)),
                ('display_order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('standing_requirement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['year_level', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('program_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_code', models.CharField(max_length=30, unique=True)),
                ('year_level', models.PositiveIntegerField()),
                ('current_semester', models.PositiveIntegerField()),
                ('section_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Section code must be 4 digits: [year_level][term(1-3)][0][section_number], e.g. 3201.', regex='^[1-9][1-3]0[1-9]$')])),
                ('status', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('first_sem', 'First Semester'), ('second_sem', 'Second Semester'), ('midterm', 'Midterm')], max_length=20)),
                ('grade_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('dropped', 'Dropped')], max_length=20)),
                ('is_credit_earned', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('prerequisite', 'Prerequisite'), ('corequisite', 'Corequisite')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='academics.course')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='academics.course')),
            ],
        ),
    ]
