# Generated by Django 6.0.4 on 2026-04-30 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curricula', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='academics.course'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.program'),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcourserecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='academics.course'),
        ),
        migrations.AddField(
            model_name='studentcourserecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='academics.student'),
        ),
        migrations.AlterUniqueTogether(
            name='courserequirement',
            unique_together={('course', 'required_course', 'requirement_type')},
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together={('curriculum', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourserecord',
            unique_together={('student', 'course', 'school_year', 'term')},
        ),
    ]
